---
abstract: 'XML::LibXML based XML::Simple clone'
author:
  - 'Mark Overmeer'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.6302, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: XML-LibXML-Simple
no_index:
  directory:
    - t
    - inc
requires:
  File::Slurp: 0
  Test::More: 0.54
  Test::Pod: 1.00
  XML::LibXML: 1.64
version: 0.92
