--- #YAML:1.0
name:                XML-LibXML-Simple
version:             0.14
abstract:            XML::LibXML based XML::Simple clone
license:             perl
author:              
    - Mark Overmeer
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    File::Slurp:                   0
    Test::More:                    0.54
    Test::Pod:                     1.00
    XML::LibXML:                   1.64
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
